export { default as AuthCard } from './lib/components/AuthCard.svelte'
export { default as RoleCard } from './lib/components/RoleCard.svelte'
export { default as DemoNavItem } from './lib/components/DemoNavItem.svelte'
export { default as SentryConfigPanel } from './lib/components/SentryConfigPanel.svelte'
export { default as SentryAnnotation } from './lib/components/SentryAnnotation.svelte'
export { default as HackerToggle } from './lib/components/HackerToggle.svelte'
export { default as FloatingBadge } from './lib/components/FloatingBadge.svelte'
export { hackerMode } from './lib/state/hacker.svelte'
export * from './lib/config/demo-config.js'
