import extractorSvelte from '@unocss/extractor-svelte'
import { defineConfig, transformerDirectives, transformerVariantGroup } from 'unocss'
import { presetRokkit } from '@rokkit/unocss'
import config from './rokkit.config.js'
import { DEFAULT_AUTH_ICONS } from 'kavach'

export default defineConfig({
	extractors: [extractorSvelte()],
	presets: [presetRokkit(config)],
	safelist: [
		...DEFAULT_AUTH_ICONS,
		// Demo platform icons (dynamic classes from platforms.ts data — must be safelisted)
		'i-auth-supabase',
		'i-auth-firebase',
		'i-auth-convex',
		'i-auth-auth0',
		'i-auth-amplify',
		'i-app-shield',
		'i-app-login',
		'i-app-logout',
		'i-app-list',
		'i-app-code-visible',
		'i-app-code-hidden',
		'bg-violet-500',
		'bg-blue-500',
		'bg-emerald-500',
		'bg-cyan-500',
		'bg-indigo-500',
		'bg-cyan-400',
		'text-cyan-400',
		'text-cyan-600',
		'bg-cyan-500/20',
		'border-cyan-500/20',
		'border-cyan-500/30',
		'border-cyan-500/40',
		'bg-cyan-500/15',
		'bg-cyan-500/10',
		'bg-indigo-600',
		'bg-indigo-100',
		'text-indigo-700',
		'text-teal-700',
		'text-indigo-600',
		'text-indigo-400',
		'bg-indigo-50',
		'text-emerald-400',
		'bg-emerald-500/10',
		'text-emerald-600',
		'bg-emerald-100',
		'text-emerald-700',
		'text-amber-400',
		'bg-amber-500',
		'bg-amber-500/10',
		'bg-amber-500/15',
		'bg-amber-500/20',
		'text-amber-600',
		'bg-amber-100',
		'text-red-400',
		'bg-red-500/10',
		'bg-red-500/15',
		'border-red-500/20',
		'bg-red-500',
		'bg-red-50',
		'text-red-500',
		'text-red-600',
		'border-red-500/40',
		'text-blue-400',
		'bg-blue-500/10',
		'text-white/5',
		'text-white/10',
		'text-white/25',
		'text-white/30',
		'text-white/40',
		'text-white/50',
		'text-white/60',
		'text-white/70',
		'text-white/80',
		'bg-white/3',
		'bg-white/5',
		'bg-white/10',
		'border-white/5',
		'border-white/8',
		'border-white/10',
		'font-mono',
		'rotate-180',
		'animate-pulse',
		'backdrop-blur',
		'backdrop-blur-sm'
	],
	transformers: [transformerDirectives(), transformerVariantGroup()]
})
