// Note: In production, these are loaded via @kavach/adapter-* packages
// For testing and development, we inline the capabilities

const ADAPTER_CAPABILITIES = {
	supabase: {
		name: 'supabase',
		displayName: 'Supabase',
		supports: {
			data: true,
			rpc: true,
			logging: true,
			magic: true,
			oauth: true,
			password: true,
			passkey: true
		},
		ddl: {
			logging: {
				table: 'audit_logs',
				getSchema: (tableName) => `CREATE TABLE ${tableName} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL,
  message TEXT NOT NULL,
  context JSONB DEFAULT '{}',
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY "Service role can manage" ON ${tableName}
  FOR ALL USING (auth.role() = 'service_role');`
			}
		}
	},
	firebase: {
		name: 'firebase',
		displayName: 'Firebase',
		supports: {
			data: false,
			rpc: false,
			logging: false,
			magic: true,
			oauth: true,
			password: true,
			passkey: true
		}
	},
	auth0: {
		name: 'auth0',
		displayName: 'Auth0',
		supports: {
			data: false,
			rpc: false,
			logging: false,
			magic: true,
			oauth: true,
			password: true,
			passkey: false
		}
	},
	amplify: {
		name: 'amplify',
		displayName: 'AWS Amplify',
		supports: {
			data: false,
			rpc: false,
			logging: false,
			magic: false,
			oauth: true,
			password: true,
			passkey: false
		}
	},
	convex: {
		name: 'convex',
		displayName: 'Convex',
		supports: {
			data: false,
			rpc: false,
			logging: false,
			magic: false,
			oauth: true,
			password: true,
			passkey: false
		}
	}
}

export const ADAPTER_REGISTRY = ADAPTER_CAPABILITIES

export function getAdapterCapabilities(adapterName) {
	return ADAPTER_REGISTRY[adapterName] ?? null
}

export function getAdapterList() {
	return Object.values(ADAPTER_REGISTRY).map((cap) => ({
		value: cap.name,
		label: cap.displayName,
		hint: formatHint(cap)
	}))
}

function formatHint(capabilities) {
	const supported = []
	const unsupported = []

	if (capabilities.supports.oauth) supported.push('OAuth')
	if (capabilities.supports.password) supported.push('Password')
	if (capabilities.supports.magic) supported.push('Magic')
	if (capabilities.supports.passkey) supported.push('Passkey')
	if (capabilities.supports.data) supported.push('Data')
	if (capabilities.supports.rpc) supported.push('RPC')
	if (capabilities.supports.logging) supported.push('Logging')

	if (!capabilities.supports.data) unsupported.push('Data')
	if (!capabilities.supports.rpc) unsupported.push('RPC')
	if (!capabilities.supports.logging) unsupported.push('Logging')

	return `${supported.join(', ')}${unsupported.length > 0 ? ` | No: ${unsupported.join(', ')}` : ''}`
}

export function getSupportedProviders(capabilities) {
	const providers = []

	if (capabilities.supports.oauth) {
		providers.push(
			{ name: 'google', label: 'Continue with Google' },
			{ name: 'github', label: 'Continue with GitHub' },
			{ name: 'azure', label: 'Continue with Azure', scopes: ['email', 'profile'] }
		)
	}

	if (capabilities.supports.magic) {
		providers.push({ mode: 'otp', name: 'magic', label: 'Email for Magic Link' })
	}

	if (capabilities.supports.password) {
		providers.push({ mode: 'password', name: 'email', label: 'Sign in using' })
	}

	return providers
}

export function getSupportedFeatures(capabilities) {
	return Object.entries(capabilities.supports)
		.filter(([, supported]) => supported)
		.map(([feature]) => feature)
}

export function isFeatureSupported(capabilities, feature) {
	return capabilities?.supports?.[feature] === true
}
