export const capabilities = {
	name: 'supabase',
	displayName: 'Supabase',
	supports: {
		data: true,
		rpc: true,
		logging: true,
		magic: true,
		oauth: true,
		password: true,
		passkey: true
	},
	ddl: {
		logging: {
			table: 'audit_logs',
			getSchema: (tableName) => `CREATE TABLE ${tableName} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL,
  message TEXT NOT NULL,
  context JSONB DEFAULT '{}',
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY "Service role can manage" ON ${tableName}
  FOR ALL USING (auth.role() = 'service_role');`
		}
	}
}
